"""add node model

Revision ID: 95b9d0425268
Revises: 
Create Date: 2025-04-08 18:03:30.012733

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95b9d0425268'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('node',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('short_name', sa.String(length=255), nullable=True),
    sa.Column('long_name', sa.String(length=255), nullable=True),
    sa.Column('macaddr', sa.String(length=17), nullable=True),
    sa.Column('hw_model', sa.Integer(), nullable=True),
    sa.Column('public_key', sa.String(length=255), nullable=True),
    sa.Column('latitude', sa.Integer(), nullable=True),
    sa.Column('longitude', sa.Integer(), nullable=True),
    sa.Column('altitude', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('node')
    # ### end Alembic commands ###
